### ISSUE TITLE
H2 tag closes with H1 ?

### ISSUE THREAD

**Issue by borislavpetrovhmcts** [hmcts/look-and-feel#93]
https://github.com/hmcts/look-and-feel/blob/948cd4c55f12f79a185378fa1badf4126bb85183/templates/look-and-feel/components/fields.njk#L120

H2 tag closes with H1 ?

**Comment by bendiggle** [comment]
Good spot @borislavpetrovhmcts. Will update now!

**Comment by bendiggle** [comment]
@borislavpetrovhmcts Closing the issue has has been fixed in this PR https://github.com/hmcts/look-and-feel/pull/94. 1.18.2 has been released with this fix
